### ISSUE TITLE
图像处理问题。

### ISSUE THREAD

**Issue by LosWinaire** [glasslucas00/MeterReadV2#2]
提取完表盘以后，由于并没有在提取出的表盘的基础上进行指针检测，而是对原图进行检测，导致背景中的长线段被误认为指针，导致读数错误！
![6_6_PointerLine](https://user-images.githubusercontent.com/114787668/193378191-1b179084-4f2d-4358-ace0-9f152902fc5a.jpg)

![abc](https://user-images.githubusercontent.com/114787668/193378405-424df0d4-b4b6-4c3a-9c51-d5795c3aec80.jpg)

**Comment by LosWinaire** [comment]
如果是在此图的基础上进行指针检测，应该就能解决问题
![6_1_imgCutCircle](https://user-images.githubusercontent.com/114787668/193378484-f2f38436-fe66-4b4d-9e08-d4b9dfbdff0b.jpg)

**Comment by glasslucas00** [comment]
已经将输入的图片修改为裁切后的图片
